language: php

php:
- 5.6
- 5.5
- 5.4
- 7.0

cache:
  directories:
  - ~/.composer

before_script:
- phpenv config-add .travis.php.ini
- composer self-update
- composer install --prefer-dist

script:
- ant

branches:
  only:
  - master
